### ISSUE TITLE
Usage when using ERC20 and ERC721

### ISSUE THREAD

**Issue by lucgerrits** [madz-lab/pandoras-box#97]
Hi, whats happening when using ERC20 and ERC721 modes ? 
Do you deploy a test ERC20 and ERC721 contract automatically or do you need to specify an address ?

**Comment by zivkovicmilos** [comment]
Hey @lucgerrits,

We covered these modes extensively in our docs:
https://docs.madz-lab.com/pandoras-box/engine/runtime/erc20

The gist of it is - the transactions for these modes are method calls (in case of ERC20 - transfer, in case of ERC721 - mint) to a contract that has been deployed beforehand by the distributor account (pandora knows the address because it facilitates this deployment)
